import type {
  BankrollPoint,
  Pick,
  Sport,
  SportStat,
  StatsOverview,
} from "./types";

const now = Date.now();
const h = (n: number) => new Date(now + n * 3600_000).toISOString();
const d = (n: number) => new Date(now + n * 86_400_000).toISOString();

export const MOCK_SPORTS: Sport[] = [
  { id: 1, slug: "futbol", name: "Fútbol", icon: "circle-dot" },
  { id: 2, slug: "baloncesto", name: "Baloncesto", icon: "circle" },
  { id: 3, slug: "tenis", name: "Tenis", icon: "circle" },
  { id: 4, slug: "futbol-americano", name: "Fútbol americano", icon: "shield" },
];

function pnl(status: Pick["status"], stake: number, odds: number): number | null {
  if (status === "won") return Math.round(stake * (odds - 1) * 100) / 100;
  if (status === "lost") return -stake;
  if (status === "void" || status === "cancelled") return 0;
  return null;
}

const raw: Array<
  Omit<Pick, "result_units" | "sport_name"> & { sport_slug: string }
> = [
  {
    id: "p1",
    sport_slug: "futbol",
    competition: "LaLiga",
    event: "Real Madrid vs Barcelona",
    market: "Línea de goles",
    market_category: "goals_lines",
    selection: "Más de 2.5 goles",
    odds: 2.1,
    closing_odds: null,
    stake: 7,
    confidence: 4,
    event_start_at: h(6),
    published_at: h(-3),
    status: "pending",
    settled_at: null,
    is_vip: false,
  },
  {
    id: "p2",
    sport_slug: "baloncesto",
    competition: "NBA",
    event: "LA Lakers vs Boston Celtics",
    market: "Hándicap",
    market_category: "handicap",
    selection: "Hándicap Lakers +4.5",
    odds: 1.91,
    closing_odds: null,
    stake: 5,
    confidence: 3,
    event_start_at: h(10),
    published_at: h(-1),
    status: "pending",
    settled_at: null,
    is_vip: false,
  },
  {
    id: "p3",
    sport_slug: "futbol",
    competition: "Serie A",
    event: "Nápoles vs Juventus",
    market: "Línea de goles",
    market_category: "goals_lines",
    selection: "Menos de 2.5 goles",
    odds: 1.95,
    closing_odds: null,
    stake: 6,
    confidence: 4,
    event_start_at: h(9),
    published_at: h(-2),
    status: "pending",
    settled_at: null,
    is_vip: true,
  },
  {
    id: "p4",
    sport_slug: "tenis",
    competition: "ATP Masters",
    event: "Alcaraz vs Zverev",
    market: "Juegos hándicap",
    market_category: "handicap",
    selection: "Alcaraz −4.5 juegos",
    odds: 1.87,
    closing_odds: null,
    stake: 4,
    confidence: 3,
    event_start_at: h(5),
    published_at: h(-7),
    status: "pending",
    settled_at: null,
    is_vip: false,
  },
  {
    id: "p5",
    sport_slug: "futbol",
    competition: "Premier League",
    event: "Arsenal vs Tottenham",
    market: "Ambos marcan",
    market_category: "btts",
    selection: "Sí",
    odds: 1.72,
    closing_odds: 1.68,
    stake: 6,
    confidence: 4,
    event_start_at: d(-1),
    published_at: d(-1.2),
    status: "won",
    settled_at: d(-0.8),
    is_vip: false,
  },
  {
    id: "p6",
    sport_slug: "baloncesto",
    competition: "NBA",
    event: "Denver Nuggets vs Phoenix Suns",
    market: "Total puntos",
    market_category: "totals",
    selection: "Más de 224.5",
    odds: 1.95,
    closing_odds: 1.9,
    stake: 5,
    confidence: 3,
    event_start_at: d(-1),
    published_at: d(-1.3),
    status: "won",
    settled_at: d(-0.9),
    is_vip: false,
  },
  {
    id: "p7",
    sport_slug: "futbol-americano",
    competition: "NFL",
    event: "Kansas City Chiefs vs Buffalo Bills",
    market: "Hándicap",
    market_category: "handicap",
    selection: "Hándicap Chiefs −2.5",
    odds: 1.9,
    closing_odds: 1.9,
    stake: 4,
    confidence: 3,
    event_start_at: d(-1),
    published_at: d(-1.4),
    status: "void",
    settled_at: d(-0.9),
    is_vip: false,
  },
  {
    id: "p8",
    sport_slug: "tenis",
    competition: "ATP 500",
    event: "Sinner vs Medvedev",
    market: "Resultado exacto",
    market_category: "other",
    selection: "Sinner gana 2-0",
    odds: 2.3,
    closing_odds: 2.45,
    stake: 3,
    confidence: 2,
    event_start_at: d(-1),
    published_at: d(-1.5),
    status: "lost",
    settled_at: d(-0.85),
    is_vip: false,
  },
];

export const MOCK_PICKS: Pick[] = raw.map((p) => ({
  ...p,
  sport_name: MOCK_SPORTS.find((s) => s.slug === p.sport_slug)?.name ?? p.sport_slug,
  result_units: pnl(p.status, p.stake, p.odds),
}));

export const MOCK_STATS_OVERVIEW: StatsOverview = {
  total_picks: 1284,
  won: 691,
  lost: 561,
  void: 32,
  staked_units: 5493,
  profit_units: 78,
  roi_pct: 14.2,
  yield_pct: 6.1,
  hit_rate_pct: 53.8,
  current_streak: 2,
  first_pick_at: "2025-09-15T00:00:00Z",
  last_pick_at: d(-0.8),
};

export const MOCK_BY_SPORT: SportStat[] = [
  {
    sport_slug: "futbol",
    sport_name: "Fútbol",
    total_picks: 612,
    staked_units: 2660,
    profit_units: 42.8,
    roi_pct: 16.1,
    yield_pct: 7.0,
    hit_rate_pct: 55.4,
  },
  {
    sport_slug: "baloncesto",
    sport_name: "Baloncesto",
    total_picks: 388,
    staked_units: 1724,
    profit_units: 23.1,
    roi_pct: 13.4,
    yield_pct: 6.0,
    hit_rate_pct: 53.1,
  },
  {
    sport_slug: "tenis",
    sport_name: "Tenis",
    total_picks: 201,
    staked_units: 962,
    profit_units: 9.4,
    roi_pct: 9.8,
    yield_pct: 4.7,
    hit_rate_pct: 51.2,
  },
  {
    sport_slug: "futbol-americano",
    sport_name: "Fútbol americano",
    total_picks: 83,
    staked_units: 366,
    profit_units: 2.7,
    roi_pct: 3.2,
    yield_pct: 3.3,
    hit_rate_pct: 49.4,
  },
];

const CUM = [0, 8, -4, -14, -6, 7, 21, 16, 34, 44, 55, 63, 78];
const MONTH_LABELS = [
  "2025-10-01",
  "2025-11-01",
  "2025-12-01",
  "2026-01-01",
  "2026-02-01",
  "2026-03-01",
  "2026-04-01",
  "2026-05-01",
  "2026-06-01",
  "2026-07-01",
  "2026-08-01",
  "2026-09-01",
  "2026-10-01",
];

export const MOCK_BANKROLL: BankrollPoint[] = CUM.map((v, i) => ({
  bucket_start: MONTH_LABELS[i],
  period_units: Math.round((v - (i > 0 ? CUM[i - 1] : 0)) * 100) / 100,
  cumulative_units: v,
}));
